/**
 * Standardized HL² Error Codes
 * @readonly
 * @enum {string}
 */
export const ERROR_CODES = {
  // Network & Transport
  NETWORK_FAILURE: 'NETWORK_FAILURE',
  REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',

  // Retailer & Provider
  RETAILER_PROVIDER_FAILURE: 'RETAILER_PROVIDER_FAILURE',
  UNSUPPORTED_RETAILER: 'UNSUPPORTED_RETAILER',

  // Product & URL Analysis
  INVALID_PRODUCT_URL: 'INVALID_PRODUCT_URL',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  AMBIGUOUS_PRODUCT_MATCH: 'AMBIGUOUS_PRODUCT_MATCH',
  STALE_PRICE: 'STALE_PRICE',
  UNAVAILABLE_PRODUCT: 'UNAVAILABLE_PRODUCT',

  // Authentication & Security
  AUTH_FAILURE: 'AUTH_FAILURE',
  EXPIRED_JWT: 'EXPIRED_JWT',
  FORBIDDEN: 'FORBIDDEN',

  // Database & Infrastructure
  DATABASE_ERROR: 'DATABASE_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  BACKGROUND_JOB_FAILURE: 'BACKGROUND_JOB_FAILURE',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
};

export default ERROR_CODES;
